name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts

      - name: Build site
        run: deno task build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v5
        with:
          build_dir: _site
          fqdn: hellojfung.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}